SELECT idmunicipios, nome FROM municipios;
 
INSERT INTO municipios (idmunicipios,nome) VALUES (201, 'Adamantina');
INSERT INTO municipios (idmunicipios,nome) VALUES (202, 'Adolfo');
INSERT INTO municipios (idmunicipios,nome) VALUES (203, 'Aguaí');
INSERT INTO municipios (idmunicipios,nome) VALUES (204, 'Águas da Prata');
INSERT INTO municipios (idmunicipios,nome) VALUES (205, 'Águas de Lindóia');
INSERT INTO municipios (idmunicipios,nome) VALUES (206, 'Águas de Santa Bárbara');
INSERT INTO municipios (idmunicipios,nome) VALUES (207, 'Águas de São Pedro');
INSERT INTO municipios (idmunicipios,nome) VALUES (208, 'Agudos');
INSERT INTO municipios (idmunicipios,nome) VALUES (209, 'Alambari');
INSERT INTO municipios (idmunicipios,nome) VALUES (210, 'Alfredo Marcondes');
INSERT INTO municipios (idmunicipios,nome) VALUES (211, 'Altair');
INSERT INTO municipios (idmunicipios,nome) VALUES (212, 'Altinópolis');
INSERT INTO municipios (idmunicipios,nome) VALUES (213, 'Alto Alegre');
INSERT INTO municipios (idmunicipios,nome) VALUES (214, 'Alumínio');
INSERT INTO municipios (idmunicipios,nome) VALUES (215, 'Álvares Florence');
INSERT INTO municipios (idmunicipios,nome) VALUES (216, 'Álvares Machado');
INSERT INTO municipios (idmunicipios,nome) VALUES (217, 'Álvaro de Carvalho');
INSERT INTO municipios (idmunicipios,nome) VALUES (218, 'Alvinlândia');
INSERT INTO municipios (idmunicipios,nome) VALUES (219, 'Americana');
INSERT INTO municipios (idmunicipios,nome) VALUES (220, 'Américo Brasiliense');
INSERT INTO municipios (idmunicipios,nome) VALUES (221, 'Américo de Campos');
INSERT INTO municipios (idmunicipios,nome) VALUES (222, 'Amparo');
INSERT INTO municipios (idmunicipios,nome) VALUES (223, 'Analândia');
INSERT INTO municipios (idmunicipios,nome) VALUES (224, 'Andradina');
INSERT INTO municipios (idmunicipios,nome) VALUES (225, 'Angatuba');
INSERT INTO municipios (idmunicipios,nome) VALUES (226, 'Anhembi');
INSERT INTO municipios (idmunicipios,nome) VALUES (227, 'Anhumas');
INSERT INTO municipios (idmunicipios,nome) VALUES (228, 'Aparecida');
INSERT INTO municipios (idmunicipios,nome) VALUES (229, 'Aparecida do Oeste');
INSERT INTO municipios (idmunicipios,nome) VALUES (230, 'Apiaí');
INSERT INTO municipios (idmunicipios,nome) VALUES (231, 'Araçariguama');
INSERT INTO municipios (idmunicipios,nome) VALUES (232, 'Araçatuba');
INSERT INTO municipios (idmunicipios,nome) VALUES (233, 'Araçoiaba da Serra');
INSERT INTO municipios (idmunicipios,nome) VALUES (234, 'Aramina');
INSERT INTO municipios (idmunicipios,nome) VALUES (235, 'Arandu');
INSERT INTO municipios (idmunicipios,nome) VALUES (236, 'Arapeí');
INSERT INTO municipios (idmunicipios,nome) VALUES (237, 'Araraquara');
INSERT INTO municipios (idmunicipios,nome) VALUES (238, 'Araras');
INSERT INTO municipios (idmunicipios,nome) VALUES (239, 'Arco-Íris');
INSERT INTO municipios (idmunicipios,nome) VALUES (240, 'Arealva');
INSERT INTO municipios (idmunicipios,nome) VALUES (241, 'Areias');
INSERT INTO municipios (idmunicipios,nome) VALUES (242, 'Areiópolis');
INSERT INTO municipios (idmunicipios,nome) VALUES (243, 'Ariranha');
INSERT INTO municipios (idmunicipios,nome) VALUES (244, 'Artur Nogueira');
INSERT INTO municipios (idmunicipios,nome) VALUES (245, 'Arujá');
INSERT INTO municipios (idmunicipios,nome) VALUES (246, 'Aspásia');
INSERT INTO municipios (idmunicipios,nome) VALUES (247, 'Assis');
INSERT INTO municipios (idmunicipios,nome) VALUES (248, 'Atibaia');
INSERT INTO municipios (idmunicipios,nome) VALUES (249, 'AuriflamaAtibaia');
INSERT INTO municipios (idmunicipios,nome) VALUES (250, 'Avaí');
INSERT INTO municipios (idmunicipios,nome) VALUES (251, 'Avanhandava');
INSERT INTO municipios (idmunicipios,nome) VALUES (252, 'Avaré');
INSERT INTO municipios (idmunicipios,nome) VALUES (253, 'Bady Bassitt');
INSERT INTO municipios (idmunicipios,nome) VALUES (254, 'Balbinos');
INSERT INTO municipios (idmunicipios,nome) VALUES (255, 'Bálsamo');
INSERT INTO municipios (idmunicipios,nome) VALUES (256, 'Bananal');
INSERT INTO municipios (idmunicipios,nome) VALUES (257, 'Barão de Antonina');
INSERT INTO municipios (idmunicipios,nome) VALUES (258, 'Barbosa');
INSERT INTO municipios (idmunicipios,nome) VALUES (259, 'Bariri');
INSERT INTO municipios (idmunicipios,nome) VALUES (260, 'Barra Bonita');
INSERT INTO municipios (idmunicipios,nome) VALUES (261, 'Barra do Chapéu');
INSERT INTO municipios (idmunicipios,nome) VALUES (262, 'Barra do Turvo');
INSERT INTO municipios (idmunicipios,nome) VALUES (263, 'Barretos');
INSERT INTO municipios (idmunicipios,nome) VALUES (264, 'Barrinha');
INSERT INTO municipios (idmunicipios,nome) VALUES (265, 'Barueri');
INSERT INTO municipios (idmunicipios,nome) VALUES (266, 'Bastos');
INSERT INTO municipios (idmunicipios,nome) VALUES (267, 'Batatais');
INSERT INTO municipios (idmunicipios,nome) VALUES (268, 'Bauru');
INSERT INTO municipios (idmunicipios,nome) VALUES (269, 'Bebedouro');
INSERT INTO municipios (idmunicipios,nome) VALUES (270, 'Bento de Abreu');
INSERT INTO municipios (idmunicipios,nome) VALUES (271, 'Bernardino de Campos');
INSERT INTO municipios (idmunicipios,nome) VALUES (272, 'Bertioga');
INSERT INTO municipios (idmunicipios,nome) VALUES (273, 'Bilac');
INSERT INTO municipios (idmunicipios,nome) VALUES (274, 'Birigui');
INSERT INTO municipios (idmunicipios,nome) VALUES (275, 'Biritibamirim');
INSERT INTO municipios (idmunicipios,nome) VALUES (276, 'Boa Esperança do Sul');
INSERT INTO municipios (idmunicipios,nome) VALUES (277, 'Bocaina');
INSERT INTO municipios (idmunicipios,nome) VALUES (278, 'Bofete');
INSERT INTO municipios (idmunicipios,nome) VALUES (279, 'Boituva');
INSERT INTO municipios (idmunicipios,nome) VALUES (280, 'Bom Jesus dos Perdões');
INSERT INTO municipios (idmunicipios,nome) VALUES (281, 'Bom Sucesso de Itararé');
INSERT INTO municipios (idmunicipios,nome) VALUES (282, 'Borá');
INSERT INTO municipios (idmunicipios,nome) VALUES (283, 'Boracéia');
INSERT INTO municipios (idmunicipios,nome) VALUES (284, 'Borborema');
INSERT INTO municipios (idmunicipios,nome) VALUES (285, 'Borebi');
INSERT INTO municipios (idmunicipios,nome) VALUES (286, 'Botucatu');
INSERT INTO municipios (idmunicipios,nome) VALUES (287, 'Bragança Paulista');
INSERT INTO municipios (idmunicipios,nome) VALUES (288, 'Braúna');
INSERT INTO municipios (idmunicipios,nome) VALUES (289, 'Brejo Alegre');
INSERT INTO municipios (idmunicipios,nome) VALUES (290, 'Brodowski');
INSERT INTO municipios (idmunicipios,nome) VALUES (291, 'Brotas');
INSERT INTO municipios (idmunicipios,nome) VALUES (292, 'Buri');
INSERT INTO municipios (idmunicipios,nome) VALUES (293, 'Buritama');
INSERT INTO municipios (idmunicipios,nome) VALUES (294, 'Buritizal');
INSERT INTO municipios (idmunicipios,nome) VALUES (295, 'Cabrália Paulista');
INSERT INTO municipios (idmunicipios,nome) VALUES (296, 'Cabreúva');
INSERT INTO municipios (idmunicipios,nome) VALUES (297, 'Caçapava');
INSERT INTO municipios (idmunicipios,nome) VALUES (298, 'Cachoeira Paulista');
INSERT INTO municipios (idmunicipios,nome) VALUES (299, 'Caconde');
INSERT INTO municipios (idmunicipios,nome) VALUES (300, 'Cafelândia');
INSERT INTO municipios (idmunicipios,nome) VALUES (301, 'Caiabu');
INSERT INTO municipios (idmunicipios,nome) VALUES (302, 'Caieras');
INSERT INTO municipios (idmunicipios,nome) VALUES (303, 'Caiuá');
INSERT INTO municipios (idmunicipios,nome) VALUES (304, 'Cajamar');
INSERT INTO municipios (idmunicipios,nome) VALUES (305, 'Cajati');
INSERT INTO municipios (idmunicipios,nome) VALUES (306, 'Cajobi');
INSERT INTO municipios (idmunicipios,nome) VALUES (307, 'Cajuru');
INSERT INTO municipios (idmunicipios,nome) VALUES (308, 'Campina do Monte Alegre');
INSERT INTO municipios (idmunicipios,nome) VALUES (309, 'Campinas');
INSERT INTO municipios (idmunicipios,nome) VALUES (310, 'Campo Limpo Paulista');
INSERT INTO municipios (idmunicipios,nome) VALUES (311, 'Campos do Jordão');
INSERT INTO municipios (idmunicipios,nome) VALUES (312, 'Campos Novos Paulista');
INSERT INTO municipios (idmunicipios,nome) VALUES (313, 'Cananéia');
INSERT INTO municipios (idmunicipios,nome) VALUES (314, 'Canas');
INSERT INTO municipios (idmunicipios,nome) VALUES (315, 'Cândido Mota');
INSERT INTO municipios (idmunicipios,nome) VALUES (316, 'Cândido Rodrigues');
INSERT INTO municipios (idmunicipios,nome) VALUES (317, 'Canitar');
INSERT INTO municipios (idmunicipios,nome) VALUES (319, 'Capão Bonito');
INSERT INTO municipios (idmunicipios,nome) VALUES (320, 'Capela do Alto');
INSERT INTO municipios (idmunicipios,nome) VALUES (321, 'Capivari');
INSERT INTO municipios (idmunicipios,nome) VALUES (322, 'Caraguatatuba');
INSERT INTO municipios (idmunicipios,nome) VALUES (323, 'Carapicuíba');
INSERT INTO municipios (idmunicipios,nome) VALUES (324, 'Cardoso');
INSERT INTO municipios (idmunicipios,nome) VALUES (325, 'Casa Branca');
INSERT INTO municipios (idmunicipios,nome) VALUES (326, 'Cássia dos Coqueiros');
INSERT INTO municipios (idmunicipios,nome) VALUES (327, 'Castilho');
INSERT INTO municipios (idmunicipios,nome) VALUES (328, 'Catanduva');
INSERT INTO municipios (idmunicipios,nome) VALUES (329, 'Catiguá');
INSERT INTO municipios (idmunicipios,nome) VALUES (330, 'Cedral');
INSERT INTO municipios (idmunicipios,nome) VALUES (331, 'Cerqueira César');
INSERT INTO municipios (idmunicipios,nome) VALUES (332, 'Cerquilho');
INSERT INTO municipios (idmunicipios,nome) VALUES (333, 'Cesário Lange');
INSERT INTO municipios (idmunicipios,nome) VALUES (334, 'Charqueada');
INSERT INTO municipios (idmunicipios,nome) VALUES (335, 'Chavantes');
INSERT INTO municipios (idmunicipios,nome) VALUES (336, 'Clementina');
INSERT INTO municipios (idmunicipios,nome) VALUES (337, 'Colina');
INSERT INTO municipios (idmunicipios,nome) VALUES (338, 'Colômbia');
INSERT INTO municipios (idmunicipios,nome) VALUES (339, 'Conchal');
INSERT INTO municipios (idmunicipios,nome) VALUES (340, 'Conchas');
INSERT INTO municipios (idmunicipios,nome) VALUES (341, 'Cordeirópolis');
INSERT INTO municipios (idmunicipios,nome) VALUES (342, 'Coroados');
INSERT INTO municipios (idmunicipios,nome) VALUES (343, 'Coronel Macedo');
INSERT INTO municipios (idmunicipios,nome) VALUES (344, 'Corumbataí');
INSERT INTO municipios (idmunicipios,nome) VALUES (345, 'Cosmópolis');
INSERT INTO municipios (idmunicipios,nome) VALUES (346, 'Cosmorama');
INSERT INTO municipios (idmunicipios,nome) VALUES (347, 'Cotia');
INSERT INTO municipios (idmunicipios,nome) VALUES (348, 'Cravinhos');
INSERT INTO municipios (idmunicipios,nome) VALUES (349, 'Cristais Paulista');
INSERT INTO municipios (idmunicipios,nome) VALUES (350, 'Cruzália');
INSERT INTO municipios (idmunicipios,nome) VALUES (351, 'Cruzeiro');
INSERT INTO municipios (idmunicipios,nome) VALUES (352, 'Cubatão');
INSERT INTO municipios (idmunicipios,nome) VALUES (353, 'Cunha');
INSERT INTO municipios (idmunicipios,nome) VALUES (354, 'Descalvado');
INSERT INTO municipios (idmunicipios,nome) VALUES (355, 'Diadema');
INSERT INTO municipios (idmunicipios,nome) VALUES (356, 'Dirce Reis');
INSERT INTO municipios (idmunicipios,nome) VALUES (357, 'Divinolândia');
INSERT INTO municipios (idmunicipios,nome) VALUES (358, 'Dobrada');
INSERT INTO municipios (idmunicipios,nome) VALUES (359, 'Dois Córregos');
INSERT INTO municipios (idmunicipios,nome) VALUES (360, 'Dolcinópolis');
INSERT INTO municipios (idmunicipios,nome) VALUES (361, 'Dourado');
INSERT INTO municipios (idmunicipios,nome) VALUES (362, 'Dracena');
INSERT INTO municipios (idmunicipios,nome) VALUES (363, 'Duartina');
INSERT INTO municipios (idmunicipios,nome) VALUES (364, 'DumontEchaporã');
INSERT INTO municipios (idmunicipios,nome) VALUES (365, 'Eldorado');
INSERT INTO municipios (idmunicipios,nome) VALUES (366, 'Elias Fausto');
INSERT INTO municipios (idmunicipios,nome) VALUES (367, 'Elisiário');
INSERT INTO municipios (idmunicipios,nome) VALUES (368, 'Embaúba');
INSERT INTO municipios (idmunicipios,nome) VALUES (369, 'Embu');
INSERT INTO municipios (idmunicipios,nome) VALUES (370, 'Embu-Guaçu');
INSERT INTO municipios (idmunicipios,nome) VALUES (371, 'Emilianópolis');
INSERT INTO municipios (idmunicipios,nome) VALUES (372, 'Engenheiro Coelho');
INSERT INTO municipios (idmunicipios,nome) VALUES (373, 'Espírito Santo do Pinhal');
INSERT INTO municipios (idmunicipios,nome) VALUES (374, 'Espírito Santo do Turvo');
INSERT INTO municipios (idmunicipios,nome) VALUES (375, 'Estiva Gerbi');
INSERT INTO municipios (idmunicipios,nome) VALUES (376, 'Estrela do Norte');
INSERT INTO municipios (idmunicipios,nome) VALUES (377, 'Estrela do Oeste');
INSERT INTO municipios (idmunicipios,nome) VALUES (378, 'Euclides da Cunha Paulista');
INSERT INTO municipios (idmunicipios,nome) VALUES (379, 'Fartura');
INSERT INTO municipios (idmunicipios,nome) VALUES (380, 'Fernando Prestes');
INSERT INTO municipios (idmunicipios,nome) VALUES (381, 'Fernandópolis');
INSERT INTO municipios (idmunicipios,nome) VALUES (382, 'Fernão');
INSERT INTO municipios (idmunicipios,nome) VALUES (383, 'Ferraz de Vasconcelos');
INSERT INTO municipios (idmunicipios,nome) VALUES (384, 'Flora Rica');
INSERT INTO municipios (idmunicipios,nome) VALUES (385, 'Floreal');
INSERT INTO municipios (idmunicipios,nome) VALUES (386, 'Flórida Paulista');
INSERT INTO municipios (idmunicipios,nome) VALUES (387, 'Florínea');
INSERT INTO municipios (idmunicipios,nome) VALUES (388, 'Franca');
INSERT INTO municipios (idmunicipios,nome) VALUES (389, 'Francisco Morato');
INSERT INTO municipios (idmunicipios,nome) VALUES (390, 'Franco da Rocha');
INSERT INTO municipios (idmunicipios,nome) VALUES (391, 'Gabriel Monteiro');
INSERT INTO municipios (idmunicipios,nome) VALUES (392, 'Gália');
INSERT INTO municipios (idmunicipios,nome) VALUES (393, 'Garça');
INSERT INTO municipios (idmunicipios,nome) VALUES (394, 'Gastão Vidigal');
INSERT INTO municipios (idmunicipios,nome) VALUES (395, 'Gavião Peixoto');
INSERT INTO municipios (idmunicipios,nome) VALUES (396, 'General Salgado');
INSERT INTO municipios (idmunicipios,nome) VALUES (397, 'Getulina');
INSERT INTO municipios (idmunicipios,nome) VALUES (398, 'Glicério');
INSERT INTO municipios (idmunicipios,nome) VALUES (399, 'Guaiçara');
INSERT INTO municipios (idmunicipios,nome) VALUES (400, 'Guaimbê');
INSERT INTO municipios (idmunicipios,nome) VALUES (401, 'Guaíra');
INSERT INTO municipios (idmunicipios,nome) VALUES (402, 'Guapiaçu');
INSERT INTO municipios (idmunicipios,nome) VALUES (403, 'Guapiara');
INSERT INTO municipios (idmunicipios,nome) VALUES (404, 'Guará');
INSERT INTO municipios (idmunicipios,nome) VALUES (405, 'Guaraçaí');
INSERT INTO municipios (idmunicipios,nome) VALUES (406, 'Guaraci');
INSERT INTO municipios (idmunicipios,nome) VALUES (407, 'Guarani do Oeste');
INSERT INTO municipios (idmunicipios,nome) VALUES (408, 'Guarantã');
INSERT INTO municipios (idmunicipios,nome) VALUES (409, 'Guararapes');
INSERT INTO municipios (idmunicipios,nome) VALUES (410, 'Guararema');
INSERT INTO municipios (idmunicipios,nome) VALUES (411, 'Guaratinguetá');
INSERT INTO municipios (idmunicipios,nome) VALUES (412, 'Guareí');
INSERT INTO municipios (idmunicipios,nome) VALUES (413, 'Guariba');
INSERT INTO municipios (idmunicipios,nome) VALUES (414, 'Guarujá');
INSERT INTO municipios (idmunicipios,nome) VALUES (415, 'Guarulhos');
INSERT INTO municipios (idmunicipios,nome) VALUES (416, 'Guatapará');
INSERT INTO municipios (idmunicipios,nome) VALUES (417, 'Guzolândia');
INSERT INTO municipios (idmunicipios,nome) VALUES (418, 'Herculândia');
INSERT INTO municipios (idmunicipios,nome) VALUES (419, 'Holambra');
INSERT INTO municipios (idmunicipios,nome) VALUES (420, 'HortolândiaIacanga');
INSERT INTO municipios (idmunicipios,nome) VALUES (421, 'Iacri');
INSERT INTO municipios (idmunicipios,nome) VALUES (422, 'Iaras');
INSERT INTO municipios (idmunicipios,nome) VALUES (423, 'Ibaté');
INSERT INTO municipios (idmunicipios,nome) VALUES (424, 'Ibirá');
INSERT INTO municipios (idmunicipios,nome) VALUES (425, 'Ibirarema');
INSERT INTO municipios (idmunicipios,nome) VALUES (426, 'Ibitinga');
INSERT INTO municipios (idmunicipios,nome) VALUES (427, 'Ibiúna');
INSERT INTO municipios (idmunicipios,nome) VALUES (428, 'Icém');
INSERT INTO municipios (idmunicipios,nome) VALUES (429, 'Iepê');
INSERT INTO municipios (idmunicipios,nome) VALUES (430, 'Igaraçu do Tietê');
INSERT INTO municipios (idmunicipios,nome) VALUES (431, 'Igarapava');
INSERT INTO municipios (idmunicipios,nome) VALUES (432, 'Igaratá');
INSERT INTO municipios (idmunicipios,nome) VALUES (433, 'Iguape');
INSERT INTO municipios (idmunicipios,nome) VALUES (434, 'Ilha Comprida');
INSERT INTO municipios (idmunicipios,nome) VALUES (435, 'Ilha Solteira');
INSERT INTO municipios (idmunicipios,nome) VALUES (436, 'Ilhabela');
INSERT INTO municipios (idmunicipios,nome) VALUES (437, 'Indaiatuba');
INSERT INTO municipios (idmunicipios,nome) VALUES (438, 'Indiana');
INSERT INTO municipios (idmunicipios,nome) VALUES (439, 'Indiaporã');
INSERT INTO municipios (idmunicipios,nome) VALUES (440, 'Inúbia Paulista');
INSERT INTO municipios (idmunicipios,nome) VALUES (441, 'Ipaussu');
INSERT INTO municipios (idmunicipios,nome) VALUES (442, 'Iperó');
INSERT INTO municipios (idmunicipios,nome) VALUES (443, 'Ipeúna');
INSERT INTO municipios (idmunicipios,nome) VALUES (444, 'Ipiguá');
INSERT INTO municipios (idmunicipios,nome) VALUES (445, 'Iporanga');
INSERT INTO municipios (idmunicipios,nome) VALUES (446, 'Ipuã');
INSERT INTO municipios (idmunicipios,nome) VALUES (447, 'Iracemápolis');
INSERT INTO municipios (idmunicipios,nome) VALUES (448, 'Irapuã');
INSERT INTO municipios (idmunicipios,nome) VALUES (449, 'Irapuru');
INSERT INTO municipios (idmunicipios,nome) VALUES (450, 'Itaberá');
INSERT INTO municipios (idmunicipios,nome) VALUES (451, 'Itaí');
INSERT INTO municipios (idmunicipios,nome) VALUES (452, 'Itajobi');
INSERT INTO municipios (idmunicipios,nome) VALUES (453, 'Itaju');
INSERT INTO municipios (idmunicipios,nome) VALUES (454, 'Itanhaém');
INSERT INTO municipios (idmunicipios,nome) VALUES (455, 'Itaóca');
INSERT INTO municipios (idmunicipios,nome) VALUES (456, 'Itapecerica da Serra');
INSERT INTO municipios (idmunicipios,nome) VALUES (457, 'Itapetininga');
INSERT INTO municipios (idmunicipios,nome) VALUES (458, 'Itapeva');
INSERT INTO municipios (idmunicipios,nome) VALUES (459, 'Itapevi');
INSERT INTO municipios (idmunicipios,nome) VALUES (460, 'Itapira');
INSERT INTO municipios (idmunicipios,nome) VALUES (461, 'Itapirapuã Paulista');
INSERT INTO municipios (idmunicipios,nome) VALUES (462, 'Itápolis');
INSERT INTO municipios (idmunicipios,nome) VALUES (463, 'Itaporanga');
INSERT INTO municipios (idmunicipios,nome) VALUES (464, 'Itapuí');
INSERT INTO municipios (idmunicipios,nome) VALUES (465, 'Itapura');
INSERT INTO municipios (idmunicipios,nome) VALUES (466, 'Itaquaquecetuba');
INSERT INTO municipios (idmunicipios,nome) VALUES (467, 'Itararé');
INSERT INTO municipios (idmunicipios,nome) VALUES (468, 'Itariri');
INSERT INTO municipios (idmunicipios,nome) VALUES (469, 'Itatiba');
INSERT INTO municipios (idmunicipios,nome) VALUES (470, 'Itatinga');
INSERT INTO municipios (idmunicipios,nome) VALUES (471, 'Itirapina');
INSERT INTO municipios (idmunicipios,nome) VALUES (472, 'Itirapuã');
INSERT INTO municipios (idmunicipios,nome) VALUES (473, 'Itobi');
INSERT INTO municipios (idmunicipios,nome) VALUES (474, 'Itu');
INSERT INTO municipios (idmunicipios,nome) VALUES (475, 'Itupeva');
INSERT INTO municipios (idmunicipios,nome) VALUES (476, 'ItuveravaJaborandi');
INSERT INTO municipios (idmunicipios,nome) VALUES (477, 'Jaboticabal');
INSERT INTO municipios (idmunicipios,nome) VALUES (478, 'Jacareí');
INSERT INTO municipios (idmunicipios,nome) VALUES (479, 'Jaci');
INSERT INTO municipios (idmunicipios,nome) VALUES (480, 'Jacupiranga');
INSERT INTO municipios (idmunicipios,nome) VALUES (481, 'Jaguariúna');
INSERT INTO municipios (idmunicipios,nome) VALUES (482, 'Jales');
INSERT INTO municipios (idmunicipios,nome) VALUES (483, 'Jambeiro');
INSERT INTO municipios (idmunicipios,nome) VALUES (484, 'Jandira');
INSERT INTO municipios (idmunicipios,nome) VALUES (485, 'Jardinópolis');
INSERT INTO municipios (idmunicipios,nome) VALUES (486, 'Jarinu');
INSERT INTO municipios (idmunicipios,nome) VALUES (487, 'Jaú');
INSERT INTO municipios (idmunicipios,nome) VALUES (488, 'Jeriquara');
INSERT INTO municipios (idmunicipios,nome) VALUES (489, 'Joanópolis');
INSERT INTO municipios (idmunicipios,nome) VALUES (490, 'João Ramalho');
INSERT INTO municipios (idmunicipios,nome) VALUES (491, 'José Bonifácio');
INSERT INTO municipios (idmunicipios,nome) VALUES (492, 'Júlio Mesquita');
INSERT INTO municipios (idmunicipios,nome) VALUES (493, 'Jumirim');
INSERT INTO municipios (idmunicipios,nome) VALUES (494, 'Jundiaí');
INSERT INTO municipios (idmunicipios,nome) VALUES (495, 'Junqueirópolis');
INSERT INTO municipios (idmunicipios,nome) VALUES (496, 'Juquiá');
INSERT INTO municipios (idmunicipios,nome) VALUES (497, 'Juquitiba');
INSERT INTO municipios (idmunicipios,nome) VALUES (498, 'Lagoinha');
INSERT INTO municipios (idmunicipios,nome) VALUES (499, 'Laranjal Paulista');
INSERT INTO municipios (idmunicipios,nome) VALUES (500, 'Lavínia');
INSERT INTO municipios (idmunicipios,nome) VALUES (501, 'Lavrinhas');
INSERT INTO municipios (idmunicipios,nome) VALUES (502, 'Leme');
INSERT INTO municipios (idmunicipios,nome) VALUES (503, 'Lençóis Paulista');
INSERT INTO municipios (idmunicipios,nome) VALUES (504, 'Limeira');
INSERT INTO municipios (idmunicipios,nome) VALUES (505, 'Lindóia');
INSERT INTO municipios (idmunicipios,nome) VALUES (506, 'Lins');
INSERT INTO municipios (idmunicipios,nome) VALUES (507, 'Lorena');

INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('508', 'Lourdes');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('509', 'Louveira');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('510', 'Lucianópolis');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('511', 'Luís Antônio');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('512', 'Luiziânia');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('513', 'Lupércio');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('514', 'Lutécia Macatuba');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('515', 'Macaubal');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('516', 'Macedônia');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('517', 'Magda');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('518', 'Mairinque');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('519', 'Mairiporã');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('520', 'Manduri');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('521', 'Marabá Paulista');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('522', 'Maracaí');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('523', 'Marapoama');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('524', 'Mariápolis');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('525', 'Marília');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('526', 'Marinópolis');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('527', 'Martinópolis');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('528', 'Matão');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('529', 'Mauá');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('530', 'Mendonça');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('531', 'Meridiano');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('532', 'Mesópolis');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('533', 'Miguelópolis');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('534', 'Mineiros do Tietê');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('535', 'Mira Estrela');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('536', 'Miracatu');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('537', 'Mirandópolis');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('538', 'Mirante do Paranapanema');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('539', 'Mirassol');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('540', 'Mirassolândia');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('541', 'Mococa');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('542', 'Mogi das Cruzes');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('543', 'Mogi Guaçu');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('544', 'Mogi Mirim');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('545', 'Mombuca');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('546', 'Monções');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('547', 'Mongaguá');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('548', 'Monte Alegre do Sul');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('549', 'Monte Alto');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('550', 'Monte Aprazível');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('551', 'Monte Azul Paulista');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('552', 'Monte Castelo');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('553', 'Monte Mor');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('554', 'Monteiro Lobato');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('555', 'Morro Agudo');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('556', 'Morungaba');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('557', 'Motuca');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('558', 'Murutinga do SulNantes');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('559', 'Narandiba');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('560', 'Natividade da Serra');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('561', 'Nazaré Paulista');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('562', 'Neves Paulista');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('563', 'Nhandeara');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('564', 'Nipoã');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('565', 'Nova Aliança');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('566', 'Nova Campina');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('567', 'Nova Canaã Paulista');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('568', 'Nova Castilho');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('569', 'Nova Europa');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('570', 'Nova Granada');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('571', 'Nova Guataporanga');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('572', 'Nova Independência');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('573', 'Nova Luzitânia');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('574', 'Nova Odessa');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('575', 'Novais');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('576', 'Novo Horizonte');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('577', 'Nuporanga Ocauçu');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('578', 'Óleo');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('579', 'Olímpia');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('580', 'Onda Verde');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('581', 'Oriente');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('582', 'Orindiúva');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('583', 'Orlândia');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('584', 'Osasco');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('585', 'Oscar Bressane');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('586', 'Osvaldo Cruz');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('587', 'Ourinhos');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('588', 'Ouroeste Pacaembu');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('589', 'Palestina');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('590', 'Palmares Paulista');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('591', 'Palmeira d\'Oeste');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('592', 'Palmital');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('593', 'Panorama');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('594', 'Paraguaçu Paulista');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('595', 'Paraibuna');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('596', 'Paraíso');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('597', 'Paranapanema');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('598', 'Paranapuã');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('599', 'Parapuã');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('600', 'Pardinho');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('601', 'Pariquera-Açu');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('602', 'Parisi');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('603', 'Patrocínio Paulista');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('604', 'Paulicéia');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('605', 'Paulínia');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('606', 'Paulistânia');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('607', 'Paulo de Faria');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('608', 'Pederneiras');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('609', 'Pedra Bela');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('610', 'Pedranópolis');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('611', 'Pedregulho');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('612', 'Pedreira');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('613', 'Pedrinhas Paulista');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('614', 'Pedro de Toledo');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('615', 'Penápolis');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('616', 'Pereira Barreto');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('617', 'Pereiras');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('618', 'Peruíbe');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('619', 'Piacatu');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('620', 'Piedade');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('621', 'Pilar do Sul');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('622', 'Pindamonhangaba');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('623', 'Pindorama');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('624', 'Pinhalzinho');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('625', 'Piquerobi');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('626', 'Piquete');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('627', 'Piracaia');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('628', 'Piracicaba');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('629', 'Piraju');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('630', 'Pirajuí');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('631', 'Pirangi');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('632', 'Pirapora do Bom Jesus');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('633', 'Pirapozinho');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('634', 'Pirassununga');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('635', 'Piratininga');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('636', 'Pitangueiras');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('637', 'Planalto');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('638', 'Platina');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('639', 'Poá');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('640', 'Poloni');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('641', 'Pompeia');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('642', 'Pongaí');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('643', 'Pontal');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('644', 'Pontalinda');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('645', 'Pontes Gestal');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('646', 'Populina');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('647', 'Porangaba');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('648', 'Porto Feliz');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('649', 'Porto Ferreira');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('650', 'Potim');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('651', 'Potirendaba');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('652', 'Pracinha');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('653', 'Pradópolis');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('654', 'Praia Grande');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('655', 'Pratânia');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('656', 'Presidente Alves');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('657', 'Presidente Bernardes');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('658', 'Presidente Epitácio');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('659', 'Presidente Prudente');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('660', 'Presidente Venceslau');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('661', 'Promissão Quadra');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('662', 'Quatá');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('663', 'Queiroz');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('664', 'Queluz');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('665', 'Quintana Rafard');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('666', 'Rancharia');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('667', 'Redenção da Serra');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('668', 'Regente Feijó');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('669', 'Reginópolis');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('670', 'Registro');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('671', 'Restinga');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('672', 'Ribeira');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('673', 'Ribeirão Bonito');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('674', 'Ribeirão Branco');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('675', 'Ribeirão Corrente');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('676', 'Ribeirão do Sul');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('677', 'Ribeirão dos Índios');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('678', 'Ribeirão Grande');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('679', 'Ribeirão Pires');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('680', 'Ribeirão Preto');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('681', 'Rifaina');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('682', 'Rincão');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('683', 'Rinópolis');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('684', 'Rio Claro');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('685', 'Rio das Pedras');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('686', 'Rio Grande da Serra');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('687', 'Riolândia');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('688', 'Riversul');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('689', 'Rosana');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('690', 'Roseira');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('691', 'Rubiácea');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('692', 'Rubinéia Sabino');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('693', 'Sagres');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('694', 'Sales');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('695', 'Sales Oliveira');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('696', 'Salesópolis');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('697', 'Salmourão');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('698', 'Saltinho');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('699', 'Salto');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('700', 'Salto de Pirapora');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('701', 'Salto Grande');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('702', 'Sandovalina');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('703', 'Santa Adélia');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('704', 'Santa Albertina');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('705', 'Santa Bárbara d\'Oeste');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('706', 'Santa Branca');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('707', 'Santa Clara d\'Oeste');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('708', 'Santa Cruz da Conceição');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('709', 'Santa Cruz da Esperança');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('710', 'Santa Cruz das Palmeiras');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('711', 'Santa Cruz do Rio Pardo');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('712', 'Santa Ernestina');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('713', 'Santa Fé do Sul');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('714', 'Santa Gertrudes');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('715', 'Santa Isabel');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('716', 'Santa Lúcia');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('717', 'Santa Maria da Serra');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('718', 'Santa Mercedes');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('719', 'Santa Rita do Passa-Quatro');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('720', 'Santa Rita d\'Oeste');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('721', 'Santa Rosa de Viterbo');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('722', 'Santa Salete');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('723', 'Santana da Ponte Pensa');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('724', 'Santana de Parnaíba');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('725', 'Santo Anastácio');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('726', 'Santo André');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('727', 'Santo Antônio da Alegria');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('728', 'Santo Antônio de Posse');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('729', 'Santo Antônio do Aracanguá');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('730', 'Santo Antônio do Jardim');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('731', 'Santo Antônio do Pinhal');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('732', 'Santo Expedito');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('733', 'Santópolis do Aguapeí');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('734', 'Santos');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('735', 'São Bento do Sapucaí');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('736', 'São Bernardo do Campo');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('737', 'São Caetano do Sul');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('738', 'São Carlos');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('739', 'São Francisco');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('740', 'São João da Boa Vista');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('741', 'São João das Duas Pontes');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('742', 'São João de Iracema');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('743', 'São João do Pau d\'Alho');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('744', 'São Joaquim da Barra');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('745', 'São José da Bela Vista');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('746', 'São José do Barreiro');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('747', 'São José do Rio Pardo');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('748', 'São José do Rio Preto');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('749', 'São José dos Campos');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('750', 'São Lourenço da Serra');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('751', 'São Luiz do Paraitinga');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('752', 'São Manuel');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('753', 'São Miguel Arcanjo');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('754', 'São Paulo');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('755', 'São Pedro');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('756', 'São Pedro do Turvo');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('757', 'São Roque');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('758', 'São Sebastião');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('759', 'São Sebastião da Grama');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('760', 'São Simão');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('761', 'São Vicente');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('762', 'Sarapuí');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('763', 'Sarutaiá');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('764', 'Sebastianópolis do Sul');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('765', 'Serra Azul');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('766', 'Serra Negra');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('767', 'Serrana');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('768', 'Sertãozinho');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('769', 'Sete Barras');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('770', 'Severínia');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('771', 'Silveiras');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('772', 'Socorro');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('773', 'Sorocaba');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('774', 'Sud Mennucci');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('775', 'Sumaré');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('776', 'Suzanápolis');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('777', 'Suzano ');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('778', 'Tabapuã');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('779', 'Tabatinga');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('780', 'Taboão da Serra');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('781', 'Taciba');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('782', 'Taguaí');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('783', 'Taiaçu');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('784', 'Taiúva');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('785', 'Tambaú');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('786', 'Tanabi');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('787', 'Tapiraí');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('788', 'Tapiratiba');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('789', 'Taquaral');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('790', 'Taquaritinga');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('791', 'Taquarituba');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('792', 'Taquarivaí');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('793', 'Tarabai');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('794', 'Tarumã');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('795', 'Tatuí');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('796', 'Taubaté');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('797', 'Tejupá');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('798', 'Teodoro Sampaio');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('799', 'Terra Roxa');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('800', 'Tietê');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('801', 'Timburi');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('802', 'Torre de Pedra');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('803', 'Torrinha');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('804', 'Trabiju');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('805', 'Tremembé');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('806', 'Tuiuti');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('807', 'Tupã');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('808', 'Tupi Paulista');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('809', 'Turiúba');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('810', 'Turmalina Ubarana');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('811', 'Ubatuba');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('812', 'Ubirajara');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('813', 'Uchoa');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('814', 'União Paulista');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('815', 'Urânia');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('816', 'Uru');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('817', 'UrupêsValentim Gentil');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('818', 'Valinhos');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('819', 'Valparaíso');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('820', 'Vargem');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('821', 'Vargem Grande do Sul');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('822', 'Vargem Grande Paulista');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('823', 'Várzea Paulista');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('824', 'Vera Cruz');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('825', 'Vinhedo');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('826', 'Viradouro');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('827', 'Vista Alegre do Alto');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('828', 'Vitória Brasil');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('829', 'Votorantim');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('830', 'Votuporanga');
INSERT INTO `niveis_abastecimento`.`municipios` (`idmunicipios`, `nome`) VALUES ('831', 'Zacarias');
